version: '3'
services:
  # Nginx server configuration
  web:
    image: nginx:1.17
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  # Php-fpm configuration
  php:
    image: php:7.2-fpm
    volumes:
      - ./src:/var/www/html
 # Mysql configuration
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
        - "13306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
